### ISSUE TITLE
Cannot build with latest VS 2017

### ISSUE THREAD

**Issue by dannyatftecu** [Microsoft/BluetoothLEExplorer#15] opened 2018-06-15 17:49 UTC
I downloaded the latest zip [6/15/2018 10AM PDT] and tried to run the project with VS 2017 V15.7.3 [on Win 10 x64 Version1803 build 17134.112].

I get warning: VS update required.  The project blew requires a platform SDK (UAP, version=10.0.17133.0) that is either not installed or is included...

I selected the oldest one on the list [I also tried the newest one as well] and I end up with all kinds of errors when building the solution:
[error.list.log](https://github.com/Microsoft/BluetoothLEExplorer/files/2107005/error.list.log)

The readme doesn't have any steps listed but is there a specific sequence of building this source?

**Comment by Sinorm** [comment] 2018-06-15 17:55
We will fix this problem in the code soon, it is caused by a SDK mismatch between the BTLEE code and the final Windows SDK version number. Edit the .csproj files to switch the target SDK from 17133 to 17134 and it will build correctly.

**Comment by CornyjK** [comment] 2018-07-06 21:07
@Sinorm Fixed by #17

**Comment by AadithyaVenkat** [comment] 2018-08-02 18:52
I am facing the same problem. My XAMl files are not being displayed and VS mentions that it has to update to a higher version of windows Win 10 x64 Version1803 build 17134.112 but I cannot update it to that version. Also changing the minimum version and target version to the ones below 17134.112 did not help, throwing errors like GattService is not being supported by those versions.

**Comment by Sinorm** [comment] 2018-08-03 00:06
You will need to be running the latest version of Windows on your developer machine, version 1803: https://www.microsoft.com/en-us/software-download/windows10 Once you are running Windows 1803 you will need the Windows 1803 SDK, then you should be able to build the application: https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

**Closed by Sinorm** 2018-08-03 00:06 UTC

**Comment by AadithyaVenkat** [comment] 2018-08-08 18:53
Unfortunately I cannot run 1803 on my machine due to restrictions. Is there a workaround for this?
